version: '3.5'
services:
  zookeeper:
    container_name: zookeeper
    build:
      context: .
      dockerfile: Dockerfile.zookeeper
    restart: always
    ports:
    - 2181:2181
    networks:
    - kafka-network
    healthcheck:
      test: ["CMD", "/home/ic/zookeeper-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      # start period provides initialization time for containers that need time to bootstrap.
      start_period: 10s
  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: Dockerfile.kafka
#    restart: always
    entrypoint: ["/bin/bash",  "/home/ic/kafka-entrypoint.sh"]
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    networks:
    - kafka-network
    healthcheck:
      test: ["CMD", "/home/ic/kafka-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      # start period provides initialization time for containers that need time to bootstrap.
      start_period: 10s
networks:
  kafka-network:
    # use the bridge driver
    driver: overlay
    name: kafka-network
    attachable: true